development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: derm_pro_app_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: derm_pro_app_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: derm_pro_app_production
  pool: 5
  username: 
  password: 
